Added a few features
tenthirtyone/blocktools pull request #8
Opened 2018-01-11 23:57 UTC by yunquliu

1. Print the time stamp in human read mode instead of unix mode
2. Parse the ScriptSig into script and InputPubkey
3. Parse the ScriptPubkey into OP_CODE and pubkeyHash
4. Added a output.txt which is a one block sample

To do so, added in a new opcode.y file

	modified:   block.py
	new file:   opcode.py
	new file:   output.txt
	modified:   sight.py

2018-01-31 20:55 UTC, AlexChambers commented
@yunquliu 
I'm wondering if @tenthirtyone has been to busy to review your PR request or if it needs to be on a named feature branch (i.e. `git push origin my-new-feature`)

2018-02-02 05:29 UTC, tenthirtyone commented
Little busy working on https://igave.io

I'll give this a look

2018-02-02 05:54 UTC, tenthirtyone requested changes
Nice work. It always bothered me I never got to the Script. Thank you

2018-02-02 05:54 UTC, tenthirtyone commented on README.md
> +This is a fork of block chain tools.
Can you credit your contribution here instead?

2018-02-02 05:55 UTC, merged

2018-03-07 16:14 UTC, yunquliu commented
My Pleasure.

 

Leon

 

发件人: Alex [mailto:notifications@github.com] 
发送时间: 2018年2月2日 13:55
收件人: tenthirtyone/blocktools <blocktools@noreply.github.com>
抄送: yunquliu <yunqu.liu@gmail.com>; Mention <mention@noreply.github.com>
主题: Re: [tenthirtyone/blocktools] Added a few features (#8)

 

@tenthirtyone requested changes on this pull request.

Nice work. It always bothered me I never got to the Script. Thank you

  _____  

In README.md <https://github.com/tenthirtyone/blocktools/pull/8#discussion_r165563531> :

> @@ -1,3 +1,9 @@
+This is a fork of block chain tools.

Can you credit your contribution here instead?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/tenthirtyone/blocktools/pull/8#pullrequestreview-93524871> , or mute the thread <https://github.com/notifications/unsubscribe-auth/AZKkwo4cA4UU6Zd7_af0zDwF5r9sK6Trks5tQqMqgaJpZM4RboMJ> .  <https://github.com/notifications/beacon/AZKkwhkx6n8zxUhUt7IDVp8azfJ7WnNrks5tQqMqgaJpZM4RboMJ.gif>